plugins {
    id("com.android.asset-pack")
}

assetPack {
    packName = "nexa_npu_pack"
    dynamicDelivery {
        deliveryType = "install-time"
    }
}

// ── Extract npu HTP assets from Nexa AAR at build time ─────────────────────────
// The Nexa SDK bundles assets/npu/htp-files-v81/ and htp-files-v85/ inside its
// AAR. We resolve the AAR artifact, unzip only those npu paths, and place them
// into this asset pack's src/main/assets/npu/ so Play Asset Delivery can serve
// them to devices at install time.
//
// This keeps the ~230 MB of QNN HTP runtime libs OUT of the base module and
// delivers them as a separate install-time asset pack, keeping base <= 200 MB.
//
// The extracted directory is .gitignored — it is always regenerated by Gradle.
// ───────────────────────────────────────────────────────────────────────────────

val nexaAar by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    // No artifact type attribute — @aar notation resolves the raw .aar file directly
}

dependencies {
    // Must match the version in :app to reuse Gradle's cached artifact
    nexaAar("ai.nexa:core:0.0.24@aar")
}

val npuAssetsDir = layout.projectDirectory.dir("src/main/assets/npu")

val extractNexaNpuAssets by tasks.registering {
    description = "Extracts npu/htp-files-v81/ and npu/htp-files-v85/ from Nexa AAR"
    group = "build setup"

    inputs.files(nexaAar)
    outputs.dir(npuAssetsDir)
    // Only re-run if the output is missing or the AAR changed
    outputs.upToDateWhen {
        npuAssetsDir.asFile.resolve("htp-files-v81").exists() &&
        npuAssetsDir.asFile.resolve("htp-files-v85").exists()
    }

    doLast {
        val aar = nexaAar.singleFile
        val outRoot = npuAssetsDir.asFile
        // Clean previous extraction so stale files don't accumulate across SDK updates
        outRoot.deleteRecursively()
        outRoot.mkdirs()

        var extracted = 0
        java.util.zip.ZipFile(aar).use { zip ->
            zip.entries().asSequence()
                .filter { !it.isDirectory && it.name.startsWith("assets/npu/htp-files-v") }
                .forEach { entry ->
                    // entry.name = "assets/npu/htp-files-v81/libQnnHtpPrepare.so"
                    // strip the "assets/" prefix → "npu/htp-files-v81/libQnnHtpPrepare.so"
                    val relPath = entry.name.removePrefix("assets/")
                    val target = outRoot.resolve(
                        relPath.removePrefix("npu/")  // place under outRoot directly
                    )
                    target.parentFile.mkdirs()
                    zip.getInputStream(entry).use { src -> target.outputStream().use { dst -> src.copyTo(dst) } }
                    extracted++
                }
        }
        logger.lifecycle("nexaNpuPack: extracted $extracted files from ${aar.name} → ${outRoot.absolutePath}")
    }
}

// Ensure extraction happens before assets are merged into the pack
tasks.configureEach {
    if (name.startsWith("merge") && name.contains("Assets", ignoreCase = true)) {
        dependsOn(extractNexaNpuAssets)
    }
}
