# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHLV_sLWoUv5eY435qcXbE1BQGKW0URy
"""

# Install deps
!pip install huggingface_hub torch absl-py numpy Pillow

# Set up HF token
from huggingface_hub import hf_hub_download
import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "HF_YOUR_TOKEN_HERE"  # replace

# Download SD v1.5 EMA checkpoints
print("Downloading SD v1.5 EMA weights…")
ckpt = hf_hub_download(
    repo_id="stable-diffusion-v1-5/stable-diffusion-v1-5",
    filename="v1-5-pruned-emaonly.safetensors"
)
print("Checkpoint at:", ckpt)

# Clone samples with converter
!git clone https://github.com/google-ai-edge/mediapipe-samples.git
!ls mediapipe-samples/tools/image_generator_converter/

# Run conversion
output_dir = "/content/sd15_mp"
!python mediapipe-samples/tools/image_generator_converter/convert.py \
    --ckpt_path "{ckpt}" \
    --output_path "{output_dir}"

print("Converted model in:", output_dir)

!find mediapipe -name convert.py

from huggingface_hub import hf_hub_download

ckpt = hf_hub_download(
    repo_id="runwayml/stable-diffusion-v1-5",
    filename="v1-5-pruned-emaonly.ckpt"
)

print(ckpt)

!python mediapipe-samples/tools/image_generator_converter/convert.py \
  --ckpt_path "/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/*/v1-5-pruned-emaonly.ckpt" \
  --output_path "/content/sd15_mp"

import glob

paths = glob.glob(
    "/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/*/v1-5-pruned-emaonly.ckpt"
)

print(paths)

!python mediapipe-samples/tools/image_generator_converter/convert.py \
  --ckpt_path "/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14/v1-5-pruned-emaonly.ckpt" \
  --output_path "/content/sd15_mp"

!sed -i \
's/th.load(ckpt_path, map_location="cpu")/th.load(ckpt_path, map_location="cpu", weights_only=False)/' \
mediapipe-samples/tools/image_generator_converter/convert.py

!python mediapipe-samples/tools/image_generator_converter/convert.py \
  --ckpt_path "/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14/v1-5-pruned-emaonly.ckpt" \
  --output_path "/content/sd15_mp"

!pip install pytorch-lightning==1.9.5

!python mediapipe-samples/tools/image_generator_converter/convert.py \
  --ckpt_path "/root/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14/v1-5-pruned-emaonly.ckpt" \
  --output_path "/content/sd15_mp"

!zip -r sd15_mediapipe_android.zip /content/sd15_mp

!cp -r /content/sd15_mp /content/drive/MyDrive/